spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # connect to service discovery (eureka server) for locate all the details microservices
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true # eureka

info:
  app:
    name: api-gateway
    description: "Easy Bank Gateway application"
    version: "1.0.0"

logging:
  level:
    org:
      interview:
        apigateway: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000