server:
  port: 8080

spring:
  application:
    name: order
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    password: "guest"
    username: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh