server:
  port: 8080

spring:
  application:
    name: order
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    password: "guest"
    username: "guest"

# actuator dependency
management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh
  endpoint:
    shutdown:
      access: unrestricted # enabled: true is deprecated
  info:
    env:
      enabled: true # eureka

# setting is no required and can be ignored
endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# show info to eureka dashboard
info:
  app:
    name: order
    description: "Easy Bank Order application"
    version: "1.0.0"