server:
  port: 8081

spring:
  application:
    name: payment
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"

# actuator dependency
management:
  endpoints:
    web:
      exposure:
        include: "*" #refresh
  endpoint:
    shutdown:
      access: unrestricted # enabled: true is deprecated
  info:
    env:
      enabled: true # eureka

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# show info to eureka dashboard
info:
  app:
    name: payment
    description: "Easy Bank Payment application"
    version: "1.0.0"